# Note that there is no "patient_id" for eICU -- patients are only differentiable during the course of a
# single health system stay. Accordingly, we set the "patient" id here as the "patientHealthSystemStayID"

patient_id_col: patientHealthSystemStayID

patient:
  dob:
    code: "DOB"
    timestamp: "dateOfBirth"
    uniquepid: "uniquepid"
  gender:
    code: ["GENDER", "col(gender)"]
    timestamp: null
  ethnicity:
    code: ["ETHNICITY", "col(ethnicity)"]
    timestamp: null
  hosp_admission:
    code:
      - "HOSPITAL_ADMISSION"
      - col("hospitalAdmitSource")
      - col("hospitalRegion")
      - col("hospitalTeachingStatus")
      - col("hospitalNumBedsCategory")
    timestamp: "hospitalAdmitTimestamp"
    hospital_id: "hospitalID"
  hosp_discharge:
    code:
      - "HOSPITAL_DISCHARGE"
      - col("hospitalDischargeStatus")
      - col("hospitalDischargeLocation")
    timestamp: "hospitalDischargeTimestamp"
  unit_admission:
    code:
      - "UNIT_ADMISSION"
      - col("unitAdmitSource")
      - col("unitStayType")
    timestamp: "unitAdmitTimestamp"
    ward_id: "wardID"
  unit_admission_weight:
    code:
      - "UNIT_ADMISSION_WEIGHT"
    timestamp: "unitAdmitTimestamp"
    numerical_value: "unitAdmissionWeight"
  unit_admission_height:
    code:
      - "UNIT_ADMISSION_HEIGHT"
    timestamp: "unitAdmitTimestamp"
    numerical_value: "unitAdmissionHeight"
  unit_discharge:
    code:
      - "UNIT_DISCHARGE"
      - col("unitDischargeStatus")
      - col("unitDischargeLocation")
    timestamp: "unitDischargeTimestamp"
  unit_discharge_weight:
    code:
      - "UNIT_DISCHARGE_WEIGHT"
    timestamp: "unitDischargeTimestamp"
    numerical_value: "unitDischargeWeight"

timestamp_format: "%Y-%m-%d %H:%M:%S"
