MEDS_cohort_dir: ???
task_name: null

subsequence_sampling_strategy: random
seq_padding_side: right

train_subset_size: null
train_subset_seed: 1

min_seq_len: null
max_seq_len: ???

do_include_patient_id: false
do_include_subsequence_indices: false
do_include_start_time_min: false

code_metadata_fp: ${MEDS_cohort_dir}/code_metadata.parquet
split_shards_fp: ${MEDS_cohort_dir}/splits.json
schema_files_root: ${MEDS_cohort_dir}/tokenize/schemas
tasks_root: ${MEDS_cohort_dir}/tasks
tensorized_root: ${MEDS_cohort_dir}/tensorized
